name: data_sources
description: Data Sources implementation
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  models:
    path: ../domain/models

  data:
    path: ../domain/data

  chopper: ^3.0.1+1
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.7.3
  chopper_generator: ^3.0.3
  json_serializable: any
