name: flutter_clean_architecture
description: Flutter Clean Architecture

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_simple_dependency_injection: ^1.0.1

  models:
    path: local_packages/domain/models

  data:
    path: local_packages/domain/data

  common:
    path: local_packages/common

  common_flutter:
    path: local_packages/common_flutter

  platform:
    path: local_packages/platform

  repositories:
    path: local_packages/repositories

  data_sources:
    path: local_packages/data_sources

  presentation:
    path: local_packages/presentation

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: any # it will inherit the version used by "flutter_test"

  mockito: 4.1.1

flutter:

  uses-material-design: true