name: models
description: Domain Model
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  test: 1.9.4

  mockito: 4.1.1

  build_runner: ^1.7.3
  json_serializable: any
