name: presentation
description: Pages and view-related classes
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  intl:
  intl_translation:

  flutter_svg: ^0.17.1

  flutter_masked_text: ^0.8.0

  mobx: ^1.0.2+2

  flutter_mobx: ^1.0.1

  models:
    path: ../domain/models

  common:
    path: ../common

  data:
    path: ../domain/data

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: 1.9.4

  mockito: 4.1.1

  build_runner:

  mobx_codegen: ^1.0.2
